CREATE DATABASE PERIPATOS;

CREATE TABLE PERIPATOS.USERS(
	username varchar(45) NOT NULL,
	password varchar(20) NOT NULL,
	enabled smallint NOT NULL,
	PRIMARY KEY(username)
);

CREATE TABLE PERIPATOS.AUTHORITIES(
	username varchar(45) NOT NULL,
	authority varchar(10) NOT NULL,
	FOREIGN KEY (username) REFERENCES PERIPATOS.USERS
);

CREATE TABLE PERIPATOS.COURSE(
	id int NOT NULL,
	name varchar(512) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE PERIPATOS.GEOLOCATION(
	id int NOT NULL,
	latitude double NOT NULL,
	longitude double NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE PERIPATOS.QUESTION(
	id int NOT NULL,
	title varchar(512) NOT NULL,
	body varchar(4096),
	PRIMARY KEY (id)
);

CREATE TABLE PERIPATOS.ANSWER(
	id int NOT NULL,
	submission_date date NOT NULL,
	body varchar(4096) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE PERIPATOS.ASSIGNMENT(
	id int NOT NULL,
	name varchar(512) NOT NULL,
	due_date date NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE PERIPATOS.USER_ASSIGNMENT(
	user_id int,
	assignment_id int,
	FOREIGN KEY (user_id) REFERENCES PERIPATOS.USER(id),
	FOREIGN KEY (assignment_id) REFERENCES PERIPATOS.ASSIGNMENT(id)
);

CREATE TABLE PERIPATOS.COURSE_USER(
	course_id int,
	user_id int,
	FOREIGN KEY (course_id) REFERENCES PERIPATOS.COURSE(id),
	FOREIGN KEY (user_id) REFERENCES PERIPATOS.USER(id)
);

CREATE TABLE PERIPATOS.COURSE_ASSIGNMENT(
	course_id int,
	assignment_id int,
	FOREIGN KEY (course_id) REFERENCES PERIPATOS.COURSE(id),
	FOREIGN KEY (assignment_id) REFERENCES PERIPATOS.ASSIGNMENT(id)
);

CREATE TABLE PERIPATOS.USER_QUESTION(
	user_id int,
	question_id int,
	FOREIGN KEY (user_id) REFERENCES PERIPATOS.USER(id),
	FOREIGN KEY (question_id) REFERENCES PERIPATOS.QUESTION(id)
);

CREATE TABLE PERIPATOS.QUESTION_GEOLOCATION(
	question_id int,
	geolocation_id int,
	FOREIGN KEY (question_id) REFERENCES PERIPATOS.QUESTION(id),
	FOREIGN KEY (geolocation_id) REFERENCES PERIPATOS.GEOLOCATION(id)
);

CREATE TABLE PERIPATOS.USER_ANSWER(
	user_id int,
	answer_id int,
	FOREIGN KEY (user_id) REFERENCES PERIPATOS.USER(id),
	FOREIGN KEY (answer_id) REFERENCES PERIPATOS.ANSWER(id)
);

CREATE TABLE PERIPATOS.ASSIGNMENT_QUESTION(
	assignment_id int,
	question_id int,
	FOREIGN KEY (assignment_id) REFERENCES PERIPATOS.ASSIGNMENT(id),
	FOREIGN KEY (question_id) REFERENCES PERIPATOS.QUESTION(id)
);

CREATE TABLE PERIPATOS.ANSWER_QUESTION_ASSIGNMENT_COURSE(
	answer_id int,
	question_id int,
	assignment_id int,
	course_id int,
	FOREIGN KEY (answer_id) REFERENCES PERIPATOS.ANSWER(id),
	FOREIGN KEY (question_id) REFERENCES PERIPATOS.QUESTION(id),
	FOREIGN KEY (assignment_id) REFERENCES PERIPATOS.ASSIGNMENT(id),
	FOREIGN KEY (course_id) REFERENCES PERIPATOS.COURSE(id)
);